#!/bin/bash -eu

# Script to be run as part of the github pre-push hook.
#
# Checks if there is a "version-like" tag being pushed
# Then checks if it matches the version tag in Cargo.toml
# Cancels the push if the tags don't match
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>

# Regexp use to decide if a git tag is a version label
version_tag_regexp='^v?[0-9]{1,4}\.[0-9]{1,4}(\.[0-9]{1,4})?.*'

# Create a string of '0' chars of appropriate length for the current git version
zero="$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')"

echo "Checking commits for version tags before push..."

# check all commits which we are pushing
while read local_ref local_oid remote_ref remote_oid; do
    #echo "Checking commit $local_oid ..."
    # skip ref deletions
    if [ "$local_oid" != "$zero" ]; then
        tags="$(git tag --points-at $local_oid)"
        if [ -n "$tags" ]; then
            while IFS= read -r tag; do
                echo "Found tag: '$tag'..."
                if [[ "$tag" =~ $version_tag_regexp ]]; then
                    echo "Tag looks like a version number. Checking if the version tag is matching in Cargo.toml"
                    current_version="$(cargo pkgid | cut -d "#" -f2)"
                    if [ "$current_version" != "$tag" ]; then
                        echo "The tag you're trying to push ($tag) does not match the version tag in Cargo.toml ($current_version)"
                        exit 1
                    fi
                    break 2; # exit from both while loops: no need to check for further tags
                fi
            done <<< "$tags"
        fi
    fi
done

echo "Checking code formatting before push..."

    if ! cargo fmt --check; then
        echo "Please run cargo fmt before pushing."
        exit 1
    fi

exit 0