name: Continuous Deployment

on:
  push:
    # tags:
    #   - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: deploy
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy
    - name: Build Binaries
      run: cargo build --verbose
    - name: Build Documentation
      run: cargo doc --no-deps --verbose
    - name: Test
      run: cargo test --verbose

  publish-doc:
    name: Publish Documentation
    runs-on: ubuntu-latest
    needs:
    - build-and-test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build Documentation
      run: cargo doc --all --no-deps
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'target/doc'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  # publish-bin:
  #   name: Release
  #   strategy:
  #     matrix:
  #       platform:
  #         - release_for: FreeBSD-x86_64
  #           os: ubuntu-20.04
  #           target: x86_64-unknown-freebsd
  #           bin: precious
  #           name: precious-FreeBSD-x86_64.tar.gz
  #           command: build

  #         - release_for: Windows-x86_64
  #           os: windows-latest
  #           target: x86_64-pc-windows-msvc
  #           bin: precious.exe
  #           name: precious-Windows-x86_64.zip
  #           command: both

  #   runs-on: ${{ matrix.platform.os }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Build binary
  #       uses: houseabsolute/actions-rust-cross@v0
  #       with:
  #         command: ${{ matrix.platform.command }}
  #         target: ${{ matrix.platform.target }}
  #         args: "--locked --release"
  #         strip: true

